Attempt to add zsh files

diff --git a/.chezmoiscripts/run_once_install-packages.sh.tmpl b/.chezmoiscripts/run_once_install-packages.sh.tmpl
--- a/.chezmoiscripts/run_once_install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_once_install-packages.sh.tmpl
@@ -1,3 +1,22 @@
 #!/bin/sh
 
+# ##############################################################################
+#
+# install dependencies
+#
+# ##############################################################################
+
+if ! command -v git &> /dev/null
+then
+    # TODO: install if not found
+    echo "git could not be found"
+    exit
+fi
+
+# ##############################################################################
+#
+# install
+#
+# ##############################################################################
+
 git clone https://github.com/zsh-users/antigen.git ~/antigen
